import { useApp } from '../store/AppContext';
import { useAsyncData } from '../hooks/useAsyncData';
import { recommendationService } from '../services/recommendationService';
import { LoadingState, ErrorState } from '../components/common/States';
import AIRecommendationCard from '../components/recommendation/AIRecommendationCard';
import StrategyCard from '../components/recommendation/StrategyCard';

export default function AIRecommendations() {
  const { selectedCrop } = useApp();
  const primary = useAsyncData(() => recommendationService.getPrimary(), []);
  const strategies = useAsyncData(() => recommendationService.getStrategyComparison(), []);

  if (primary.status === 'loading' || strategies.status === 'loading') return <LoadingState label="Analyzing selling strategies…" />;
  if (primary.status === 'error' || strategies.status === 'error') return <ErrorState onRetry={() => { primary.refetch(); strategies.refetch(); }} />;

  return (
    <div className="flex flex-col gap-6">
      <div className="rounded-2xl border border-[var(--color-soil-200)] bg-white p-4 text-sm text-[var(--color-soil-600)]">
        This is a frontend simulation for <strong className="text-[var(--color-soil-950)]">{selectedCrop.name}</strong> using mock recommendation data. In production, this is generated by Agrovision's ML/AI recommendation engine.
      </div>

      <AIRecommendationCard recommendation={primary.data} />

      <div>
        <h2 className="mb-1 font-display text-lg font-semibold text-[var(--color-soil-950)]">Compare selling strategies</h2>
        <p className="mb-4 text-sm text-[var(--color-soil-600)]">Where, when, how much, and why — compared side by side.</p>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {strategies.data.strategies.map((s) => (
            <StrategyCard key={s.id} strategy={s} />
          ))}
        </div>
      </div>
    </div>
  );
}
